//////////////////////////// logs at my-2.1, 202 //////////////////////////////////////////
(.env-my-2.1) ody@ody-utuntu24:~/github/portfolio-0.7.6/my-2.1$ java -jar bin/jserv-album-0.7.6.jar
[INSTALL-CHECK] checking ...
============= Semantic.DA 1.5 built on 2025-06-04 =============
...

. . . . . . . . Synodtier Jetty Application is running . . . . . . .
Synode my-2-1
http://18           :8921/jserv-album
█████████████████████████████████████████
...

[docsyn : my-2] update peer my-2-1's jserv: http://18           :8921/jserv-album [2025-10-29 03:49:20]
[io.oz.jserv.docs.syn.singleton.AppSettings#updateDB_exceptMe()] [ERROR, if not the first boot] !!! This error is tolerated for running tests!
Updating jserv not exist? Shouldn't reach here!
...

[docsyn]
delete from syn_peers where peer = 'my-2-hub' AND domain = 'my-2'
insert into syn_peers (synid, peer, domain, nyq) values ('my-2-2', 'my-2-hub', 'my-2', 0), ('my-2-hub', 'my-2-hub', 'my-2', 0), ('my-2-1', 'my-2-hub', 'my-2', 0)
[docsyn]
select pagex, ch.*, sb.synodee from syn_change ch join syn_exchange_buf bf on ch.cid = bf.changeId AND 'my-2-hub' = bf.peer AND 0 = bf.pagex join syn_subscribe sb on ch.cid = sb.changeId order by synoder asc, tabl asc, seq asc
====== my-2-1 -> my-2-hub ====== Challenge Page: ======
my-2-1
page-index: 0,  challenging size (all subscribers): 0
Syntities:

[docsyn]
select pagex, ch.*, sb.synodee from syn_change ch join syn_exchange_buf bf on ch.cid = bf.changeId AND 'my-2-hub' = bf.peer AND 1 = bf.pagex join syn_subscribe sb on ch.cid = sb.changeId order by synoder asc, tabl asc, seq asc
====== my-2-1 -> my-2-hub ====== Challenge Page: ======
my-2-1
page-index: 1,  challenging size (all subscribers): 0
Syntities:

====== my-2-1 <- my-2-hub ====== Answering: ======
my-2-1
page-index: 0,  challenging size: 1
Syntities:

////////////////////////  [ssh connection sleeped at here. Starting again failed] ///////////////////////////////////

(.env-my-2.1) ody@ody-utuntu24:~/github/portfolio-0.7.6/my-2.1$ ls vol
dictionary.json  doc-jserv.db  jserv-main.db  syntity.json
(.env-my-2.1) ody@ody-utuntu24:~/github/portfolio-0.7.6/my-2.1$ java -jar bin/jserv-album-0.7.6.jar
[INSTALL-CHECK] checking ...
============= Semantic.DA 1.5 built on 2025-06-04 =============
Initializing Configs. filename: WEB-INF, xml-dir: config.xml
...

. . . . . . . . Synodtier Jetty Application is running . . . . . . .
Synode my-2-1
http://18           :8921/jserv-album
█████████████████████████████████████████
...

[docsyn]
select pagex, ch.*, sb.synodee from syn_change ch join syn_exchange_buf bf on ch.cid = bf.changeId AND 'my-2-hub' = bf.peer AND 1 = bf.pagex join syn_subscribe sb on ch.cid = sb.changeId order by synoder asc, tabl asc, seq asc
====== my-2-1 -> my-2-hub ====== Challenge Page: ======
my-2-1
page-index: 1,  challenging size (all subscribers): 0
Syntities:

jar:file:/home/ody/github/portfolio-0.7.6/my-2.1/bin/jserv-album-0.7.6.jar!/io/odysz/semantic/meta/syn_sessions.sqlite.ddl
io.odysz.semantics.x.SemanticException: Code: exSemantic, mesage:
my-2-1
        at io.odysz.jclient.HttpServClient.post(HttpServClient.java:188)
        at io.odysz.jclient.SessionClient.commit(SessionClient.java:463)
        at io.oz.jserv.docs.syn.SynssionPeer.exespush(SynssionPeer.java:348)
        at io.oz.jserv.docs.syn.SynssionPeer.exespush(SynssionPeer.java:336)
        at io.oz.jserv.docs.syn.SynssionPeer.update2peer(SynssionPeer.java:208)
        at io.oz.jserv.docs.syn.SynDomanager.synUpdateDomain(SynDomanager.java:400)
        at io.oz.jserv.docs.syn.ExpSynodetier.lambda$syn_worker$2(ExpSynodetier.java:298)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
[ ♻.✩ my-2-1 ] Synssion Opened (clientier created): {conn: docsyn, mode: peer, peer: my-2-hub, peer-jserv: http://182.150.29.34:8920/jserv-album}
[io.oz.jserv.docs.syn.SynDomanager#synodeNetworking()] Submitting jservs in my-2, check login state to: my-2-1 -> my-2-hub, jserv: http://182.150.29.34:8920/jserv-album
jar:file:/home/ody/github/portfolio-0.7.6/my-2.1/bin/jserv-album-0.7.6.jar!/io/odysz/semantic/meta/syn_sessions.sqlite.ddl
[docsyn]
select pagex, ch.*, sb.synodee from syn_change ch join syn_exchange_buf bf on ch.cid = bf.changeId AND 'my-2-hub' = bf.peer AND 1 = bf.pagex join syn_subscribe sb on ch.cid = sb.changeId order by synoder asc, tabl asc, seq asc

///////////////////////// The same error is repeating ///////////////////////////////
...

//////////////////////////// logs at my-2.0, 201 //////////////////////////////////////////

. . . . . . . . Synodtier Jetty Application is running . . . . . . .
Synode my-2-hub
http://18           :8920/jserv-album
█████████████████████████████████████████
...

[docsyn]
delete from syn_peers where peer = 'my-2-1' AND domain = 'my-2'
insert into syn_peers (synid, peer, domain, nyq) values ('my-2-2', 'my-2-1', 'my-2', 0), ('my-2-hub', 'my-2-1', 'my-2', 0), ('my-2-1', 'my-2-1', 'my-2', 0)
[docsyn]
select pagex, ch.*, sb.synodee from syn_change ch join syn_exchange_buf bf on ch.cid = bf.changeId AND 'my-2-1' = bf.peer AND 0 = bf.pagex join syn_subscribe sb on ch.cid = sb.changeId order by synoder asc, tabl asc, seq asc
====== my-2-hub -> my-2-1 ====== Challenge Page: ======
my-2-hub
page-index: 0,  challenging size (all subscribers): 12
Syntities:

h_photos,       size: 3,
====== my-2-hub <- my-2-1 ====== Answering: ======
my-2-hub
page-index: 0,  challenging size: 0
Syntities:

h_photos        1
Sesssion refeshed. Session(s) idled (expired) in last 60 minutes:    ///////////////////////// This is the sign support the conclusion
[07s2IVJq, org.my : my-2-1 : admin]
...

[docsyn]
delete from syn_peers where peer = 'my-2-1' AND domain = 'my-2'
insert into syn_peers (synid, peer, domain, nyq) values ('my-2-2', 'my-2-1', 'my-2', 0), ('my-2-hub', 'my-2-1', 'my-2', 0), ('my-2-1', 'my-2-1', 'my-2', 0)
[docsyn]
delete from syn_peers where peer = 'my-2-1' AND domain = 'my-2'
insert into syn_peers (synid, peer, domain, nyq) values ('my-2-2', 'my-2-1', 'my-2', 0), ('my-2-hub', 'my-2-1', 'my-2', 0), ('my-2-1', 'my-2-1', 'my-2', 0)
java.sql.BatchUpdateException: batch entry 0: [SQLITE_CONSTRAINT_PRIMARYKEY] A PRIMARY KEY constraint failed (UNIQUE constraint failed: syn_exchange_buf.peer, syn_exchange_buf.changeId, syn_exchange_buf.pagex)
        at org.sqlite.jdbc3.JDBC3Statement.executeLargeBatch(JDBC3Statement.java:239)
        at org.sqlite.jdbc3.JDBC3Statement.executeBatch(JDBC3Statement.java:219)
        at io.odysz.semantic.DA.drvmnger.SqliteDriverQueued.lambda$new$0(SqliteDriverQueued.java:44)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_PRIMARYKEY] A PRIMARY KEY constraint failed (UNIQUE constraint failed: syn_exchange_buf.peer, syn_exchange_buf.changeId, syn_exchange_buf.pagex)
        at org.sqlite.core.DB.newSQLException(DB.java:1179)
        at org.sqlite.core.DB.newSQLException(DB.java:1190)
        at org.sqlite.core.DB.execute(DB.java:985)
        at org.sqlite.core.DB.executeUpdate(DB.java:1054)
        at org.sqlite.jdbc3.JDBC3Statement.executeLargeBatch(JDBC3Statement.java:236)
        ... 3 more
[docsyn]
delete from syn_peers where peer = 'my-2-1' AND domain = 'my-2'
insert into syn_peers (synid, peer, domain, nyq) values ('my-2-2', 'my-2-1', 'my-2', 0), ('my-2-hub', 'my-2-1', 'my-2', 0), ('my-2-1', 'my-2-1', 'my-2', 0)
java.sql.BatchUpdateException: batch entry 0: [SQLITE_CONSTRAINT_PRIMARYKEY] A PRIMARY KEY constraint failed (UNIQUE constraint failed: syn_exchange_buf.peer, syn_exchange_buf.changeId, syn_exchange_buf.pagex)
        at org.sqlite.jdbc3.JDBC3Statement.executeLargeBatch(JDBC3Statement.java:239)
        at org.sqlite.jdbc3.JDBC3Statement.executeBatch(JDBC3Statement.java:219)
        at io.odysz.semantic.DA.drvmnger.SqliteDriverQueued.lambda$new$0(SqliteDriverQueued.java:44)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_PRIMARYKEY] A PRIMARY KEY constraint failed (UNIQUE constraint failed: syn_exchange_buf.peer, syn_exchange_buf.changeId, syn_exchange_buf.pagex)
        at org.sqlite.core.DB.newSQLException(DB.java:1179)
        at org.sqlite.core.DB.newSQLException(DB.java:1190)
        at org.sqlite.core.DB.execute(DB.java:985)
        at org.sqlite.core.DB.executeUpdate(DB.java:1054)
        at org.sqlite.jdbc3.JDBC3Statement.executeLargeBatch(JDBC3Statement.java:236)
        ... 3 more

/////////////////////////////// The same error repeated many times ///////////////////////////////////////////

The Hypothesis:

The ssh client's desktop went to sleep, and led the jetty server interrupted.

1. Google AI:

When an SSH client's desktop goes into sleep mode, the SSH connection to the
server can be interrupted, potentially leading to the termination of processes
launched directly within that SSH session on the server.

Specifically, if you started a Java application directly in an SSH session and
your client desktop goes to sleep, the following can happen:

SSH Session Interruption:
  The sleep mode on your client machine can cause the network connection to drop
  or become unreliable, leading to the SSH session being disconnected or hanging.

SIGHUP Signal:
  By default, when an SSH session terminates, the shell associated with that
  session sends a SIGHUP (hangup) signal to all its child processes.

Java App Termination:
  Unless specifically handled, a Java application (or any other process)
  receiving a SIGHUP signal will typically terminate.

2. The tables at my-2-hub:

syn_peers:

  peer  |synid   |nyq|domain|
  ------+--------+---+------+
  my-2-1|my-2-2  |0  |my-2  |
  my-2-1|my-2-hub|0  |my-2  |
  my-2-1|my-2-1  |0  |my-2  |

syn_sessions:

  peer  |chpage|answerx|expansx|mode|state|
  ------+------+-------+-------+----+-----+
  my-2-1|     0|      0|      0|   0|    2|

syn_change:

  cid |domain|tabl    |crud|synoder |uids         |nyquence|updcols                                       |seq|
  ----+------+--------+----+--------+-------------+--------+----------------------------------------------+---+
  0001|my-2  |h_photos|I   |my-2-hub|my-2-hub,0101|1       |                                              |1  |
  0002|my-2  |h_photos|U   |my-2-hub|my-2-hub,0101|1       |css,geox,mime,geoy,opertime,oper,filesize,exif|2  |
  0003|my-2  |h_photos|I   |my-2-hub|my-2-hub,0102|1       |                                              |1  |
  0004|my-2  |h_photos|U   |my-2-hub|my-2-hub,0102|1       |css,geox,mime,geoy,opertime,oper,filesize,exif|2  |
  0005|my-2  |h_photos|I   |my-2-hub|my-2-hub,0103|1       |                                              |1  |
  0006|my-2  |h_photos|U   |my-2-hub|my-2-hub,0103|1       |css,geox,mime,geoy,opertime,oper,filesize,exif|2  |

syn_subscribe:

  changeId|synodee|
  --------+-------+
  0001    |my-2-1 |
  0001    |my-2-2 |
  0002    |my-2-1 |
  0002    |my-2-2 |
  0003    |my-2-1 |
  0003    |my-2-2 |
  0004    |my-2-1 |
  0004    |my-2-2 |
  0005    |my-2-1 |
  0005    |my-2-2 |
  0006    |my-2-1 |
  0006    |my-2-2 |

syn_exchange_buf:

  peer  |changeId|pagex|
  ------+--------+-----+
  my-2-1|0001    |    0|
  my-2-1|0002    |    0|
  my-2-1|0003    |    0|
  my-2-1|0004    |    0|
  my-2-1|0005    |    0|
  my-2-1|0006    |    0|
  my-2-1|0001    |   -1|
  my-2-1|0002    |   -1|
  my-2-1|0003    |   -1|
  my-2-1|0004    |   -1|
  my-2-1|0005    |   -1|
  my-2-1|0006    |   -1|

h_photos:

  pid |family|folder |docname          |uri |pdate              |device|shareby|sharedate |tags|geox|geoy|mime      |filesize|shareflag|oper |opertime           |syncstamp          |io_oz_synuid |
  ----+------+-------+-----------------+----+-------------------+------+-------+----------+----+----+----+----------+--------+---------+-----+-------------------+-------------------+-------------+
  0101|org.my|2025-02|1738389730001.jpg|... |2025-02-01 14:02:10|0001  |admin  |2025-10-29|    |null|null|image/jpeg|  595828|publish  |admin|2025-10-29 03:21:45|2025-10-29 03:21:45|my-2-hub,0101|
  0102|org.my|2025-10|1761441385034.jpg|... |2025-10-26 09:16:25|0001  |admin  |2025-10-29|    |null|null|image/jpeg|  827393|publish  |admin|2025-10-29 03:21:46|2025-10-29 03:21:46|my-2-hub,0102|
  0103|org.my|2025-02|1738390261734.jpg|... |2025-02-01 14:11:01|0001  |admin  |2025-10-29|    |null|null|image/jpeg|  648092|publish  |admin|2025-10-29 03:21:47|2025-10-29 03:21:47|my-2-hub,0103|

3. The tables from my-2.1 are ignored for lazyness

4. Partially verified:
   h_photos synchronized correctly, with doc-ref resolving bugs to be fixed.

//////////////////////////////// conclusion ///////////////////////////////
0.7.6 is vulnerable to network breakdown.

///// fixed
- force syn_node.org = synconfig.org.orgId, for avoid steping wrong nyquence at booting.
- modify synode.py3/SynodeConfig.overlay(), only accept jserv from parameter 'by'.

///// TODO

re-ping hub

to be continued: invoke make