bugs in joining test, but step forward for verifying other design:
1 X <- join - Y
===============

[no-jserv.00]
insert into syn_node (synid, mac, nyq, domain, io_oz_synuid, org) values ('Y', '#Y', 0, 'zsu', 'Y,Y', 'URA')
insert into syn_change (tabl, crud, synoder, uids, nyquence, seq, domain, cid) values ('syn_node', 'I', 'X', 'Y,Y', 1, 1, 'zsu', 'X.0007')
insert into syn_subscribe (changeId, synodee) select 'X.0007', synid from syn_node  where synid <> 'X' AND synid <> 'Y' AND domain = 'zsu'
[no-jserv.00]
select * from syn_node syn where synid in ('Y', 'X') AND domain = 'zsu' AND org = 'URA'
[no-jserv.01]
insert into syn_node (synid, mac, nyq, domain, io_oz_synuid, org, jserv) values ('X', '#X', 0, 'zsu', 'X,X', 'URA', 'http://192.168.0.73:8090')
java.sql.BatchUpdateException: batch entry 0:
[SQLITE_CONSTRAINT_PRIMARYKEY] A PRIMARY KEY constraint failed (UNIQUE constraint failed: syn_node.org, syn_node.domain, syn_node.synid)
at org.sqlite.jdbc3.JDBC3Statement.executeLargeBatch(JDBC3Statement.java:239)
at org.sqlite.jdbc3.JDBC3Statement.executeBatch(JDBC3Statement.java:219)
at io.odysz.semantic.DA.drvmnger.SqliteDriverQueued.lambda$0(SqliteDriverQueued.java:44)
at java.base/java.lang.Thread.run(Thread.java:842)
Caused by: org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_PRIMARYKEY] A PRIMARY KEY constraint failed (UNIQUE constraint failed: syn_node.org, syn_node.domain, syn_node.synid)
at org.sqlite.core.DB.newSQLException(DB.java:1179)
at org.sqlite.core.DB.newSQLException(DB.java:1190)
at org.sqlite.core.DB.execute(DB.java:985)
at org.sqlite.core.DB.executeUpdate(DB.java:1054)
at org.sqlite.jdbc3.JDBC3Statement.executeLargeBatch(JDBC3Statement.java:236)