Refector testSynodetierJoin.testSynodetierJoin(), by using procedure of SynotierJettyApp.main().
There are testing error which is tolerated in MVP version:

[no-jserv.00]
insert into syn_node (synid, mac, nyq, domain, io_oz_synuid, org) values ('Y', '#Y', 2, 'zsu', 'Y,Y', 'ura')
insert into syn_change (tabl, crud, synoder, uids, nyquence, seq, domain, cid) values ('syn_node', 'I', 'X', 'Y,Y', 3, 1, 'zsu', 'X.0002')
insert into syn_subscribe (changeId, synodee) select 'X.0002', synid from syn_node  where synid <> 'X' AND synid <> 'Y' AND domain = 'zsu'
java.sql.BatchUpdateException: batch entry 0: [SQLITE_CONSTRAINT_PRIMARYKEY] A PRIMARY KEY constraint failed (UNIQUE constraint failed: syn_node.org, syn_node.domain, syn_node.synid)
	at org.sqlite.jdbc3.JDBC3Statement.executeLargeBatch(JDBC3Statement.java:239)
	at org.sqlite.jdbc3.JDBC3Statement.executeBatch(JDBC3Statement.java:219)
	at io.odysz.semantic.DA.drvmnger.SqliteDriverQueued.lambda$0(SqliteDriverQueued.java:44)
	at java.base/java.lang.Thread.run(Thread.java:842)
Caused by: org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_PRIMARYKEY] A PRIMARY KEY constraint failed (UNIQUE constraint failed: syn_node.org, syn_node.domain, syn_node.synid)
	at org.sqlite.core.DB.newSQLException(DB.java:1179)
	at org.sqlite.core.DB.newSQLException(DB.java:1190)
	at org.sqlite.core.DB.execute(DB.java:985)
	at org.sqlite.core.DB.executeUpdate(DB.java:1054)
	at org.sqlite.jdbc3.JDBC3Statement.executeLargeBatch(JDBC3Statement.java:236)
	... 3 more
[no-jserv.00]
select * from syn_node syn where synid in ('Y', 'X') AND domain = 'zsu' AND org = 'ura'
[no-jserv.01]
insert into syn_node (synid, mac, nyq, domain, io_oz_synuid, org, jserv) values ('X', '#X', 2, 'zsu', 'X,X', 'ura', 'http://192.168.101.5:8964/jserv-album')
java.sql.BatchUpdateException: batch entry 0: [SQLITE_CONSTRAINT_PRIMARYKEY] A PRIMARY KEY constraint failed (UNIQUE constraint failed: syn_node.org, syn_node.domain, syn_node.synid)
	at org.sqlite.jdbc3.JDBC3Statement.executeLargeBatch(JDBC3Statement.java:239)
	at org.sqlite.jdbc3.JDBC3Statement.executeBatch(JDBC3Statement.java:219)
	at io.odysz.semantic.DA.drvmnger.SqliteDriverQueued.lambda$0(SqliteDriverQueued.java:44)
	at java.base/java.lang.Thread.run(Thread.java:842)
Caused by: org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_PRIMARYKEY] A PRIMARY KEY constraint failed (UNIQUE constraint failed: syn_node.org, syn_node.domain, syn_node.synid)
	at org.sqlite.core.DB.newSQLException(DB.java:1179)
	at org.sqlite.core.DB.newSQLException(DB.java:1190)
	at org.sqlite.core.DB.execute(DB.java:985)
	at org.sqlite.core.DB.executeUpdate(DB.java:1054)
	at org.sqlite.jdbc3.JDBC3Statement.executeLargeBatch(JDBC3Statement.java:236)
	... 3 more

This is an error of configuration changes after registration strategy modified. (And will be changed in the near future)