Hunting the bug 1:
1. infor-9.1 always creates a shadow rocord,
============================================

with uri64 is a docref envelope, e.g.

{"type": "io.odysz.semantic.meta.DocRef",
 "synoder": "infor-8-hub",
 "docId": "0101", "syntabl": "h_photos",
 "uri64": "$VOLUME_HOME/inforise/admin/2025-11/0101 Screenshot_20251107_123220_com.autonavi.minimap.jpg",
 "breakpoint": 0,
 "uids": "infor-8-1,0101", "pname": "Screenshot_20251107_123220_com.autonavi.minimap.jpg"}

2. infor-9.2 cannot lock hub even infor-9.1 & hub session expired in 60 minutes.
================================================================================

Dec 29 17:07:44 ody-utuntu24 java[4027929]: Sesssion refeshed. Session(s) idled (expired) in last 60 minutes:                     z/semantic/meta/syn_sessions.sqlite.ddl
Dec 29 17:07:44 ody-utuntu24 java[4027929]: [2YV517ZW, inforise : null : admin]                                                   z/semantic/meta/syn_sessions.sqlite.ddl
Dec 29 17:07:44 ody-utuntu24 java[4027929]: [+i2YCSFW, inforise : infor-9-1 : admin]                                              z/semantic/meta/syn_sessions.sqlite.ddl
Dec 29 17:08:44 ody-utuntu24 java[4027929]: Sesssion refeshed. Session(s) idled (expired) in last 60 minutes:                     z/semantic/meta/syn_sessions.sqlite.ddl
Dec 29 17:08:44 ody-utuntu24 java[4027929]: [0qXoj9WV, inforise : infor-9-1 : admin]                                              z/semantic/meta/syn_sessions.sqlite.ddl
Dec 29 17:08:44 ody-utuntu24 java[4027929]: [1ucIs8v8, inforise : null : admin]

Endless loop in:

SyndomContext {
	public synchronized void unlockx(SyncUser usr) {
		notNull(usr);
		notNull(usr.deviceId());

		if (synlocker != null && eq(synlocker.sessionId(), usr.sessionId())) {
			musteqi(sylock[0], 1);
			sylock[0] = 0;
			if (dbg) Utils.warn(
					f("++ ++ unlocked %s <- %s\nuser: %s, ssid: %s",
					synode, usr.deviceId(), synlocker.uid(), synlocker.ssid));

			usr.domx = null;
			synlocker.domx = null;
			synlocker = null;
		}
    }
}

But goes through after:

Dec 29 17:10:44 ody-utuntu24 java[4027929]: Sesssion refeshed. Session(s) idled (expired) in last 60 minutes:
Dec 29 17:10:44 ody-utuntu24 java[4027929]: [z-ryIeZn, inforise : infor-9-1 : admin]
Dec 29 17:11:44 ody-utuntu24 java[4027929]: Sesssion refeshed. Session(s) idled (expired) in last 60 minutes:
Dec 29 17:11:44 ody-utuntu24 java[4027929]: [xYOYGEGT, inforise : infor-9-1 : admin]
Dec 29 17:11:44 ody-utuntu24 java[4027929]: [46lhFSgI, inforise : infor-9-1 : admin]
Dec 29 17:12:44 ody-utuntu24 java[4027929]: Sesssion refeshed. Session(s) idled (expired) in last 60 minutes:
Dec 29 17:12:44 ody-utuntu24 java[4027929]: [wir-Y08a, inforise : infor-9-1 : admin]
Dec 29 17:13:44 ody-utuntu24 java[4027929]: Sesssion refeshed. Session(s) idled (expired) in last 60 minutes:
Dec 29 17:13:44 ody-utuntu24 java[4027929]: [0b-T1UH0, inforise : infor-9-1 : admin]
Dec 29 17:13:44 ody-utuntu24 java[4027929]: [xvEwxju6, inforise : infor-9-1 : admin]
Dec 29 17:14:44 ody-utuntu24 java[4027929]: Sesssion refeshed. Session(s) idled (expired) in last 60 minutes:
Dec 29 17:14:44 ody-utuntu24 java[4027929]: [-ihYrzZM, inforise : infor-9-1 : admin]
Dec 29 17:15:44 ody-utuntu24 java[4027929]: Sesssion refeshed. Session(s) idled (expired) in last 60 minutes:
Dec 29 17:15:44 ody-utuntu24 java[4027929]: [pFjzYKGh, inforise : infor-9-1 : admin]
Dec 29 17:16:44 ody-utuntu24 java[4027929]: Sesssion refeshed. Session(s) idled (expired) in last 60 minutes:
Dec 29 17:16:44 ody-utuntu24 java[4027929]: [-+Ej5Rka, inforise : null : admin]
Dec 29 17:16:44 ody-utuntu24 java[4027929]: [yWB2T+N2, inforise : null : admin]
Dec 29 17:17:44 ody-utuntu24 java[4027929]: Sesssion refeshed. Session(s) idled (expired) in last 60 minutes:
Dec 29 17:17:44 ody-utuntu24 java[4027929]: [-oF2iFS0, inforise : infor-9-1 : admin]
Dec 29 17:17:44 ody-utuntu24 java[4027929]: [2YJGckc1, inforise : infor-9-1 : admin]
Dec 29 17:18:44 ody-utuntu24 java[4027929]: Sesssion refeshed. Session(s) idled (expired) in last 60 minutes:
Dec 29 17:18:44 ody-utuntu24 java[4027929]: [0wUnkyn9, inforise : infor-9-1 : admin]
Dec 29 17:18:44 ody-utuntu24 java[4027929]: [zeTmruHm, inforise : null : admin]
Dec 29 17:19:44 ody-utuntu24 java[4027929]: Sesssion refeshed. Session(s) idled (expired) in last 60 minutes:
Dec 29 17:19:44 ody-utuntu24 java[4027929]: [BikK6Q1i, inforise : infor-9-1 : admin]
Dec 29 17:19:44 ody-utuntu24 java[4027929]: [ygfiCvo5, inforise : infor-9-1 : admin]

Fixed with changing ss-timeout (to be verified).

3. Replace a Synode at the same host:port
=========================================

io.odysz.semantics.x.SemanticException: Code: exSemantic, mesage:
req.exblock.srcnode is identical to this synode's.
	at io.odysz.jclient.HttpServClient.post(HttpServClient.java:188)
	at io.odysz.jclient.SessionClient.commit(SessionClient.java:463)
	at io.oz.jserv.docs.syn.SynssionPeer.exchangeDBservs(SynssionPeer.java:1049)
	at io.oz.jserv.docs.syn.SynDomanager.synodeNetworking(SynDomanager.java:280)
	at io.oz.jserv.docs.syn.ExpSynodetier.lambda$syn_worker$2(ExpSynodetier.java:290)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

Cause:
Re-install infor-10.2 at the same host:port of infor-10.1, after stopped infor-10.1.

Fix:

	public HashMap<String, String[]> exchangeDBservs(HashMap<String, String[]> jservs)
			throws SemanticException, AnsonException, IOException {
		// e.g. infor-10.1 jserv == infor-10.2 jserv
		if (!eq(jservs.get(peer)[0], jservs.get(domanager.synode)[0])) {
			...
		}
		else return jservs; // of course the target is myselve's
	}

4. TODO c_nodes.port is always 0