1. Fixed: version numbers are not correctly handeled while making. 2. Pin point down to course of error when first start after installation, with exists volume.
Reproduce:

in deploy-y201
rm * -rf
pip src.synodepy3
load registry Y201
click save, close the window (don't install & start service)
start Eclipse debug configuration: y201 (workfolder: deploy-y201)

Error:

[INSTALL-CHECK]
!!! FIRST TIME INITIATION !!!
Install: Calling setupdb() with configurations in config.xml ...
[io.odysz.semantic.DATranscxt#initConfigs()] Loading semantics of connection sys
[io.odysz.semantic.DATranscxt#initConfigs()] Loading semantics of connection sys
Loading syntities registry: C:\Users\Alice\github\semantic-jserv\jserv-album\vol-Y201\syntity.json
Initializing synode singleton with configuration file config.xml
runtime root: .
configure folder: WEB-INF
root-key length: 16
Initializing Configs. filename: WEB-INF, xml-dir: config.xml
fullpath: WEB-INF\config.xml
config file : C:\Users\Alice\github\semantic-jserv\jserv-album\deploy-y201\WEB-INF\config.xml
Initializing connects with path to WEB-INF
Configuration root path: WEB-INF
Runtime root path: .
Initializing session with default jdbc connection sys ...
[AnSession] timeout = 60 minutes (configure: WEB-INF\config.xml)
[ServFlags.session] SSession debug mode true (ServFlage.session)
SessionChecker: timeout = 60 minute
io.odysz.semantic.meta.AutoSeqMeta.ddlSqlite, table: oz_autoseq
io.odysz.semantic.meta.SynodeMeta.ddlSqlite, table: syn_node
io.odysz.semantic.meta.SynChangeMeta.ddlSqlite, table: syn_change
io.odysz.semantic.meta.SynSubsMeta.ddlSqlite, table: syn_subscribe
io.odysz.semantic.meta.SynchangeBuffMeta.ddlSqlite, table: syn_exchange_buf
io.odysz.semantic.meta.PeersMeta.ddlSqlite, table: syn_peers
io.odysz.semantic.meta.SynSessionMeta.ddlSqlite, table: syn_sessions

java.sql.BatchUpdateException: batch entry 0: [SQLITE_ERROR] SQL error or missing database (table doc_devices already exists)
	at org.sqlite.jdbc3.JDBC3Statement.executeLargeBatch(JDBC3Statement.java:239)
	at org.sqlite.jdbc3.JDBC3Statement.executeBatch(JDBC3Statement.java:219)
	at io.odysz.semantic.DA.drvmnger.SqliteDriverQueued.lambda$new$0(SqliteDriverQueued.java:44)
	at java.base/java.lang.Thread.run(Thread.java:842)
Caused by: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (table doc_devices already exists)
	at org.sqlite.core.DB.newSQLException(DB.java:1179)
	at org.sqlite.core.DB.newSQLException(DB.java:1190)
	at org.sqlite.core.DB.throwex(DB.java:1150)
	at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
	at org.sqlite.core.NativeDB.prepare(NativeDB.java:132)
	at org.sqlite.core.DB.prepare(DB.java:264)
	at org.sqlite.jdbc3.JDBC3Statement.executeLargeBatch(JDBC3Statement.java:235)
	... 3 more
java.sql.BatchUpdateException: batch entry 0: [SQLITE_ERROR] SQL error or missing database (table "h_photos" already exists)
	at org.sqlite.jdbc3.JDBC3Statement.executeLargeBatch(JDBC3Statement.java:239)
	at org.sqlite.jdbc3.JDBC3Statement.executeBatch(JDBC3Statement.java:219)
	at io.odysz.semantic.DA.drvmnger.SqliteDriverQueued.lambda$new$0(SqliteDriverQueued.java:44)
	at java.base/java.lang.Thread.run(Thread.java:842)
Caused by: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (table "h_photos" already exists)
	at org.sqlite.core.DB.newSQLException(DB.java:1179)
	at org.sqlite.core.DB.newSQLException(DB.java:1190)
	at org.sqlite.core.DB.throwex(DB.java:1150)
	at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
	at org.sqlite.core.NativeDB.prepare(NativeDB.java:132)
	at org.sqlite.core.DB.prepare(DB.java:264)
	at org.sqlite.jdbc3.JDBC3Statement.executeLargeBatch(JDBC3Statement.java:235)

=================================================
Calling stacks:

SemanticTableMeta.setupSqlitables(String, boolean, Iterable<SyntityMeta>) line: 133
Syngleton.setupSyntables(SynodeConfig, Iterable<SyntityMeta>, String, String, String, String, boolean...) line: 267
AppSettings.setupdb(SynodeConfig, String, String, String, String, boolean) line: 120
AppSettings.setupdb(String, String, SynodeConfig, boolean) line: 85
AppSettings.checkInstall(String, String, String, String, boolean) line: 417
SynotierJettyApp._main(String[]) line: 215
SynotierJettyApp.main(String[]) line: 196

Troubleshooting:
ddl of table doc_devices and h_photos must avoid creating table if exists.

To be verified.