[Reaching Milestone] 0.7.6
update syn_node set jserv='http://192.         :8963/jserv-album' where synid = 'MOB' AND domain = 'zsu'
java.lang.NullPointerException: Cannot assign field "peerjserv" because the return value of "io.oz.jserv.docs.syn.SynDomanager.synssion(String)" is null
	at io.oz.jserv.docs.syn.SynDomanager.updateJserv(SynDomanager.java:309)
	at io.oz.jserv.docs.syn.ExpSynodetier.onReportJserv(ExpSynodetier.java:459)
  ...
io.odysz.semantics.x.SemanticException: Code: exGeneral, mesage:
java.lang.NullPointerException\nCannot assign field \"peerjserv\" because the return value of \"io.oz.jserv.docs.syn.SynDomanager.synssion(String)\" is null
	at io.odysz.jclient.HttpServClient.post(HttpServClient.java:187)
	at io.odysz.jclient.SessionClient.commit(SessionClient.java:461)
	at io.oz.jserv.docs.syn.SynssionPeer.submitJserv(SynssionPeer.java:898)
	at io.oz.jserv.docs.syn.SynDomanager.submitJservsPersist(SynDomanager.java:351)
	at io.oz.jserv.docs.syn.singleton.Syngleton.lambda$3(Syngleton.java:460)
	at java.base/java.lang.Thread.run(Thread.java:842)
[io.oz.jserv.docs.syn.SynDomanager#submitJservsPersist()] Cannot log into PRV <- MOB, for submitting my jserv, as no jservs available.
Exposing locally by io.oz.syntier.serv.T_WebservExposer, web-dist/private/host.json ...
IP 192.0.0.0 : 2025-08-13 19:30:16
Cannot find domain zsu's jserv per synode configuration.
Exposing target domain zsu != null, the current domain.
Exposed service to web-dist/private/host.json

✓ semantic-jserv: remove DoctUtils.resolvePrivRoot()

✓ Fix error by Ubuntu auto-update, of which jspawnhelper reports error while calling exiftool.

X Wait jetty-winsrv for registering online

  Not now.

✓ syn_node.remarks, SynodeMode vs. Central

  deprecate SynodeMode.leaf, add SynodeMode.hub;
  use syn_node.remarks to save SynodeMode (only the hub node is needed);
  Note: do not confuse SynodeMode.hub with Central service.

✓ update/submit/perist/query jservs...

  There are even satuations of which systems are running while network adapters have been changed configurations.
  - load proxy from settings,
  - update/expose ip from time to time

✓ fix: normalize use / reference of ext-file's path

  DocreateHandler.onCreat() -> EnvPath.decodeUri()
  ->
  DocreateHandler.onCreat() -> DocUtils.resolveExtRoot()